services:
  # Backend Service (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # It's better to use an .env file for secrets
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - FEISHU_REDIRECT_URI=${FEISHU_REDIRECT_URI:-http://frontend:5173/auth/callback}
      - FEISHU_BASE_URL=${FEISHU_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - app-network

  # Frontend Service (Vue + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # We serve from Nginx's port 80 to host's 5173
    environment:
      - VITE_API_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
