apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-repo/feishu-report-frontend:latest # IMPORTANT: Replace with your actual image repository
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feishu-report-ingress
  annotations:
    # Use 'nginx.ingress.kubernetes.io/rewrite-target: /' for NGINX Ingress Controller
    # Annotations depend on the ingress controller you are using
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: feishu-report.your-domain.com # IMPORTANT: Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      # You might also want to route /api to the backend service here
      # - path: /api
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: backend-service
      #       port:
      #         number: 8080 